apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fullstack-app
  name: fullstack-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullstack-app
  strategy: {}
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
      - image: ryansaad85/devops-pipeline:0754d61a85b4224b1ce805100608d408d6ff3a3c
        name: devops-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-service
spec:
  selector:
    app: fullstack-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  